# Generated by Django 4.1.5 on 2023-02-02 17:03

from django.db import migrations, models


def default_settings(apps, schema_editor):
    settings = Settings(
        source='bee/static/bee/video/bee.mp4',
        weights='Yolov5_StrongSORT_OSNet/weights/model.pt',
        img_size_x='1280',
        img_size_y='720',
        tracking_method='ocsort',
        start_time='2023-1-23 08:00:00',
        device='0'
    )
    settings.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('visit', models.IntegerField()),
                ('visit_pollen', models.IntegerField()),
                ('leave', models.IntegerField()),
                ('leave_pollen', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
                ('weights', models.CharField(max_length=300)),
                ('tracking_method', models.CharField(max_length=300)),
                ('img_size_x', models.IntegerField()),
                ('img_size_y', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('device', models.IntegerField()),
            ],
        ),
        migrations.RunPython(default_settings)
    ]
